### ISSUE TITLE
Maps of Himachal Pradesh

### ISSUE THREAD

**Issue by nissabasim** [tcpd/lokdhaba#32]
None of the maps of Himachal Pradesh is loading.

**Comment by chinuhub** [comment]
In Himachal's shapefile there is no column named as 'ASSEMBLY'. This breaks the code because we merge the data with map based on this key. In that file, the column was named as 'ASSEMBLY_N'. For the time being I have changed the code to handle this but we need to change the shapefile (by correcting this attribute back to 'ASSEMBLY'). In this way there will be a uniformity in the column names of all shape files.

**Comment by chinuhub** [comment]
@nissabasim Could you please check if it has been fixed in the current deployment?

**Comment by surabhimitra** [comment]
@nissabasim Can You please look into it

**Comment by hangal** [comment]
@mohitkharb has resolved this, so closing.
